### PR TITLE
Update: add parentNode prop to Popover

### PR DESCRIPTION
**Pull request by jrios**
Add parentNode to set the node with which to create the React portal.

### CODE REVIEW

**Comment by stevematney** [comment]
Would this be a case for `useRootNode`(https://github.com/WTW-IM/es-components/blob/master/packages/es-components/src/components/util/useRootNode.js)? Or possibly defaulting to using the rootnode if a `parentNode` prop isn't set?

**Comment by jrios** [comment]
I tried using `useRootNode`, but for some reason it was still defaulting to `document.body` when I was testing it out.

**Comment by jrios** [comment]
Also, `parentNode` will always be set. it defaults to `document.body` which is what it was using before.

**Comment by stevematney** [comment]
> I tried using `useRootNode`, but for some reason it was still defaulting to `document.body` when I was testing it out.

I think there's a way to do this, but you'd have to override `renderTrigger` in order to make the `ref` function do the right thing for the popover, and also the right thing for setting the `rootNodeRef`. Doing that would make it so the user would never need to provide a `parentNode`, but it would definitely add some complication here.

**Pull request merged**
