### PR TITLE
Fix Modal Scrolling

### LINKED ISSUE #471: Modal no longer scrolls content
The modal used to work properly when in mobile viewports: it should fill the space but also allow scrolling of content that goes off the screen. It still seems to fill the screen but scrolling is no longer working.

Also seems to be affecting full screen as well.

image

### PR DESCRIPTION
**Pull request by stevematney**
This is a large rework of Modals that resolves #471.

Modals now:
* Scroll within themselves in full-width (mobile) view with a fixed header
* Position themselves with their center at about 1/3 down the page.
* Animate correctly
* Scroll within themselves when they are at 100% of the window height (without a fixed header when not in full-width view)

### CODE REVIEW

**Comment by stevematney** [comment]
This PR also resolves a WAVE tool/accessibility issue where we would get an error when the Text Addons were buttons. Changing them to divs gives us all the same functionality as before, but the addons are no longer focusable, and they no longer throw any errors. (The focus simply moves directly into the input or next focusable thing, rather than to the addon.)

**Comment by Darrken** [comment]
If I'm recalling correctly the addon had `type="button"` so the datepicker would pop up when you clicked the calendar icon. I didn't realize it was causing WAVE errors so even if it does break that it may be worth the tradeoff.

**Comment by stevematney** [comment]
> If I'm recalling correctly the addon had type="button" so the datepicker would pop up when you clicked the calendar icon.

Looking at it locally, this functionality still seems to work.

**Comment by Darrken** [comment]
Are the scrollbars intentional?
image

**Comment by stevematney** [comment]
> Are the scrollbars intentional?
🤦‍♂️ Not exactly. I just don't use a mouse with a scroll wheel. I think I can get rid of them.

**Comment by stevematney** [comment]
> If you can address the scrollbar issue, then I think it's all set. 👍

[This commit](https://github.com/WTW-IM/es-components/pull/476/commits/f0654bf58627e8b37755bd54286251dd3d1a4945) should resolve the scrollbar issue.

**Comment by Darrken** [comment]
It's better! :) It's still there when content overflows in desktop view, whereas the mobile view looks perfect. I know it used to work like the [UX one here](https://wtw-im.github.io/bda-des-sys/containers.html#modals)  on desktop too.... (Click the "launch reguler[sic] modal" button)

I'm still okay with this for now though since it works!

image

**Pull request merged**
