### PR TITLE
Update: tooltip attaches to body element

### PR DESCRIPTION
**Pull request by Darrken**
This optional prop creates the tooltip on the document body element rather than as a sibling to the tooltip link.

### CODE REVIEW

**Comment by jrios** [comment]
Is there any reason that this shouldn't be the default behavior? If not, consider not adding a prop to control it and allowing the component to do it this way always.

**Comment by Darrken** [comment]
The only reason I didn't default it was to maintain backward behavior. But it probably would be safe to do so, if you find this pattern preferable.

**Comment by jrios** [comment]
Is the behavior different? Aside from where it goes in the document, is anything different?

**Comment by Darrken** [comment]
Nope.

**Comment by jrios** [comment]
in that case there's no backwards compatible behavior to worry about. :)

**Comment by Darrken** [comment]
You talked me into it. :)

**Comment by Darrken** [comment]
Any other concerns holding this up?

**Pull request merged**
