### PR TITLE
New: dateInput component

### PR DESCRIPTION
**Pull request by Darrken**
Reviewed by UX.

image
image

### CODE REVIEW

**Comment by jrios** [comment]
I will be pulling this down to check it out, but I think I can already tell that I am going to like it!

**Comment by jrios** [comment]
I really like the way this functions. I wanna hear your thoughts on this. Rather than having a prop control the inputs and the way they render, what do you think about making them components instead.

```
<DateInput>
  <DayInput />
  <MonthInput />
  <YearInput />
</DateInput>
```

You could use still maintain a lot of the functionality but you wouldn't have to worry about the order internally. You already have the components, you'd just have to expose them. 

I'm good with it either way. I think this looks great!

**Comment by Darrken** [comment]
That might make for a little cleaner code. I'm having a little bit of trouble thinking through how the onChange processes would go with them being separate, but it probably just hasn't clicked yet. 

One of the things I'm doing when re-ordering is applying the `id` to the first visual-ordered component so when the label is clicked, it's the one that gets focus. How might that work if they're individual components? `DateInput` could get the `id` and pass it to the first sub-component I suppose...

**Comment by jrios** [comment]
I think you could still do that with the label, right?

```
return (
  {React.Children.map((child, index) => (
    {index === 0 ? React.cloneElement(child, { id }) : React.cloneElement(child)}
  )}
)
```

**Comment by Darrken** [comment]
Took a bit of work, but I got it split up. I think it worked out pretty well. I also added the export to `index.js` I forgot. Hah.

**Comment by jrios** [comment]
This looks great! I have one concern. You say in the docs:

>  You may omit Month and/or Day, but Year is required.

When I remove the Year component, it doesn't have any apparent ill effects. Is that something we should be concerned about?

**Comment by Darrken** [comment]
It should have one effect, and that is that it won't return a valid date in
the onChange event if no year is present. Were you able to get one?

**Comment by jrios** [comment]
Ah, I do get `undefined`. I missed it. :shipit:

**Pull request merged**
