### PR TITLE
Added props to allow numeric keyboard on mobile

### PR DESCRIPTION
**Pull request by jswaldon**

### CODE REVIEW

**Comment by jrios** [comment]
Do these actually need to be props? Any additional props get attached to the input by default so doing something like `<Textbox inputMode="numeric" />` should work out of the box. 

Is that not the case?

**Comment by jswaldon** [comment]
it didn't appear to work when I initially tried it without specifying the props. It was the only reason I added them manually.

**Comment by Darrken** [comment]
This isn't necessary; both Textbox and MaskedTextbox pass this prop through. I tested it on the demo site. You may have forgotten to use the proper casing for react (`inputMode`)?

image

**Comment by Darrken** [comment]
`pattern` also gets passed through.

**Comment by jrios** [comment]
I'm' going to close this. It's unnecessary because those props can be passed directly into `Textbox` as @Darrken has pointed out.

**Pull request closed without merging**
