### PR TITLE
Build package as UMD

### LINKED ISSUE #76: Ship UMD Build
Ship a UMD build so we can use [Unpkg](https://unpkg.com/#/) to host over a CDN.

### PR DESCRIPTION
**Pull request by aabenoja**
[src/index.js](https://github.com/TWExchangeSolutions/es-components/blob/8541b8bf41b5e731caaf8d280ff732a07ecfe6a9/src/index.js) now compiles into

```js
(function (global, factory) {
  if (typeof define === "function" && define.amd) {
    define(['exports', './components/base/icons/Icon', './components/containers/notification/Notification', './components/containers/drawer/Drawer', './components/containers/fieldset/Fieldset', './components/containers/tooltip/Tooltip', './components/containers/popover/PopoverLink', './components/containers/modal/Modal', './components/controls/Label', './components/controls/textbox/Textbox', './components/controls/buttons/Button', './components/controls/radio-buttons/RadioGroup', './components/controls/dropdown/Dropdown', './components/controls/datepicker/DatePicker', './components/controls/checkbox/Checkbox', './components/navigation/sidenav/SideNav', './components/patterns/datepicker-textbox/DatePickerTextbox', './components/patterns/incrementer/Incrementer'], factory);
  } else if (typeof exports !== "undefined") {
    factory(exports, require('./components/base/icons/Icon'), require('./components/containers/notification/Notification'), require('./components/containers/drawer/Drawer'), require('./components/containers/fieldset/Fieldset'), require('./components/containers/tooltip/Tooltip'), require('./components/containers/popover/PopoverLink'), require('./components/containers/modal/Modal'), require('./components/controls/Label'), require('./components/controls/textbox/Textbox'), require('./components/controls/buttons/Button'), require('./components/controls/radio-buttons/RadioGroup'), require('./components/controls/dropdown/Dropdown'), require('./components/controls/datepicker/DatePicker'), require('./components/controls/checkbox/Checkbox'), require('./components/navigation/sidenav/SideNav'), require('./components/patterns/datepicker-textbox/DatePickerTextbox'), require('./components/patterns/incrementer/Incrementer'));
  } else {
    var mod = {
      exports: {}
    };
    factory(mod.exports, global.Icon, global.Notification, global.Drawer, global.Fieldset, global.Tooltip, global.PopoverLink, global.Modal, global.Label, global.Textbox, global.Button, global.RadioGroup, global.Dropdown, global.DatePicker, global.Checkbox, global.SideNav, global.DatePickerTextbox, global.Incrementer);
    global.index = mod.exports;
  }
})(this, function (exports, _Icon2, _Notification2, _Drawer2, _Fieldset2, _Tooltip2, _PopoverLink2, _Modal2, _Label2, _Textbox2, _Button2, _RadioGroup2, _Dropdown2, _DatePicker2, _Checkbox2, _SideNav2, _DatePickerTextbox2, _Incrementer2) {
  'use strict';

  Object.defineProperty(exports, "__esModule", {
    value: true
  });
  exports.Incrementer = exports.DatePickerTextbox = exports.SideNav = exports.Checkbox = exports.DatePicker = exports.Dropdown = exports.RadioGroup = exports.Button = exports.Textbox = exports.Label = exports.Modal = exports.PopoverLink = exports.Tooltip = exports.Fieldset = exports.Drawer = exports.Notification = exports.Icon = undefined;

  var _Icon3 = _interopRequireDefault(_Icon2);

  var _Notification3 = _interopRequireDefault(_Notification2);

  var _Drawer3 = _interopRequireDefault(_Drawer2);

  var _Fieldset3 = _interopRequireDefault(_Fieldset2);

  var _Tooltip3 = _interopRequireDefault(_Tooltip2);

  var _PopoverLink3 = _interopRequireDefault(_PopoverLink2);

  var _Modal3 = _interopRequireDefault(_Modal2);

  var _Label3 = _interopRequireDefault(_Label2);

  var _Textbox3 = _interopRequireDefault(_Textbox2);

  var _Button3 = _interopRequireDefault(_Button2);

  var _RadioGroup3 = _interopRequireDefault(_RadioGroup2);

  var _Dropdown3 = _interopRequireDefault(_Dropdown2);

  var _DatePicker3 = _interopRequireDefault(_DatePicker2);

  var _Checkbox3 = _interopRequireDefault(_Checkbox2);

  var _SideNav3 = _interopRequireDefault(_SideNav2);

  var _DatePickerTextbox3 = _interopRequireDefault(_DatePickerTextbox2);

  var _Incrementer3 = _interopRequireDefault(_Incrementer2);

  function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : {
      default: obj
    };
  }

  exports.Icon = _Icon3.default;
  exports.Notification = _Notification3.default;
  exports.Drawer = _Drawer3.default;
  exports.Fieldset = _Fieldset3.default;
  exports.Tooltip = _Tooltip3.default;
  exports.PopoverLink = _PopoverLink3.default;
  exports.Modal = _Modal3.default;
  exports.Label = _Label3.default;
  exports.Textbox = _Textbox3.default;
  exports.Button = _Button3.default;
  exports.RadioGroup = _RadioGroup3.default;
  exports.Dropdown = _Dropdown3.default;
  exports.DatePicker = _DatePicker3.default;
  exports.Checkbox = _Checkbox3.default;
  exports.SideNav = _SideNav3.default;
  exports.DatePickerTextbox = _DatePickerTextbox3.default;
  exports.Incrementer = _Incrementer3.default;
});
```

Closes #76

### CODE REVIEW

**Comment by aabenoja** [comment]
With these changes we can pull through unpkg with `unpkg.com/es-components`.

**Comment by Darrken** [comment]
This is pretty awesome.  Should we add a blurb to the readme.md on consuming it this way?  It might be worth noting that the icons won't work without including the font manually.

**Comment by jrios** [comment]
We should probably still include the commonjs build in addition to the UMD build. I think adding it to the README is a good idea, too.

**Comment by jrios** [comment]
I think I am going to implement Rollup for this functionality so we can deliver both a UMD build and a module build easily.

**Pull request closed without merging**
